# -*- coding: utf-8 -*-
"""extension1fastai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKdHeTHZjSGIi_roZ_yI4-RB5vLhthOa
"""

!pip install -U fastai

from fastai.text.all import *

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

dir = Path("/content/drive/Shareddrives/CIS530/data")
list(dir.glob("*"))

dls = TextDataLoaders.from_csv(path=dir, csv_fname="games_with_preprocessed_tweets_all.csv", 
                               text_col="ALL_TWEETS", label_col="HOME_TEAM_WINS")

learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)

learn.fine_tune(4, 1e-2)

learn.lr_find()

learn.fine_tune(4, 2.75422871709452e-06)

preds, targs = learn.get_preds()
x, y = learn.dls.valid_ds

??learn.dls.valid_ds

dls.valid_ds[0][1]

np.argmax(preds, axis=1)

from sklearn.metrics import f1_score, accuracy_score

f1_score(targs, np.argmax(preds, axis=1))

accuracy_score(targs, np.argmax(preds, axis=1))

